// <auto-generated />
using Hangar18.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hangar18.Data.Migrations
{
    [DbContext(typeof(Hangar18DdContext))]
    [Migration("20240518203925_Parent_box_id_is_no_longer_mandatory")]
    partial class Parent_box_id_is_no_longer_mandatory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hangar18.Data.Box", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PalletId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParentBoxId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PalletId");

                    b.HasIndex("ParentBoxId");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("Hangar18.Data.Pallet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Pallets");
                });

            modelBuilder.Entity("Hangar18.Data.Box", b =>
                {
                    b.HasOne("Hangar18.Data.Pallet", "Pallet")
                        .WithMany("Boxes")
                        .HasForeignKey("PalletId");

                    b.HasOne("Hangar18.Data.Box", "ParentBox")
                        .WithMany()
                        .HasForeignKey("ParentBoxId");

                    b.Navigation("Pallet");

                    b.Navigation("ParentBox");
                });

            modelBuilder.Entity("Hangar18.Data.Pallet", b =>
                {
                    b.Navigation("Boxes");
                });
#pragma warning restore 612, 618
        }
    }
}
